name: awsimagecaption
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  bloc_pattern: ^2.5.1
  flutter_simple_dependency_injection: ^1.0.2+1
  intl: ^0.16.1
  http: ^0.12.1
  crypto: ^2.1.4
  xml: ^4.1.0
  json_serializable: ^3.3.0
  retrofit: ^1.3.4
  floor: ^0.12.0
  rxdart: ^0.24.0
  equatable: ^1.1.1
  image_picker: ^0.6.7
  fade: ^1.0.0
  shared_aws_api: ^0.1.5
  flutter_tts: ^1.2.2
  aws_lambda_dart_runtime: ^1.0.3+1
  web_socket_channel: ^1.1.0
  audiofileplayer: ^1.3.1

dev_dependencies:
  json_serializable: ^3.3.0
  retrofit_generator: ^1.3.4+1
  floor_generator: ^0.12.0
  build_runner: ^1.7.3

flutter:
  uses-material-design: true
  fonts:
    - family:  AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf